# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "tok-dl"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- .Arch }}_
      {{- .Version }}
    format_overrides:
      - goos: windows
        formats:
          - zip

dockers:
  - id: amd64
    ids:
      - tok-dl
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/sweepies/tok-dl:latest
      - ghcr.io/sweepies/tok-dl:{{ .Version }}
    skip_push: auto
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

  - id: arm64
    ids:
      - tok-dl
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/sweepies/tok-dl:latest-arm64
      - ghcr.io/sweepies/tok-dl:{{ .Version }}-arm64
    skip_push: auto
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ops:"
      - "^style:"
